"""Materialize datasets/intelehealth-verify-v3 Harbor task directories.

Generated files are owned by this script. Run twice for identical output.
Does not write datasets/intelehealth-verify-v2.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SHARED = ROOT / "shared"
sys.path.insert(0, str(SHARED))

from protocol_walker import load_protocol  # noqa: E402
from v3_fixtures import DEMO_RULES, iter_cases, manifest_payload, validate_case  # noqa: E402

GENERATED = "Generated by shared/build_v3_tasks.py. Do not edit by hand."
V3_ROOT = ROOT / "datasets" / "intelehealth-verify-v3"
PROTOCOL_SRC = ROOT / "data" / "Chest pain.json"
GRADER_FILES = ("protocol_walker.py", "grade.py", "encounter.py", "proposal_schema.json")

STUB_AGENT = '''"""Stub intake walker. Generated by shared/build_v3_tasks.py. Do not edit by hand.

Asks the first legal unanswered question. When none remain, closes using
CLOSE_DISPOSITION. Set that assignment; do not rewrite propose().
"""

from __future__ import annotations

from typing import Any

CLOSE_DISPOSITION = ""  # agent must set local_management | refer | urgent


def propose(state: dict[str, Any], protocol: Any) -> dict[str, Any]:
    age = int(state["age"])
    answers = state.get("answers") or []
    answered = {a["question_id"] for a in answers if a.get("question_id")}
    selected: set[str] = set()
    for answer in answers:
        selected.update(answer.get("option_ids") or [])
    legal = protocol.get_legal_next_questions(selected, answered, age)
    if not legal:
        return {
            "schema_version": "0.1.0",
            "protocol_id": protocol.name,
            "action": "close_and_act",
            "disposition": CLOSE_DISPOSITION,
        }
    question = legal[0]
    option_ids = [
        o.id
        for o in protocol.options_for(question.id)
        if protocol.is_age_eligible(o, age)
    ]
    return {
        "schema_version": "0.1.0",
        "protocol_id": protocol.name,
        "action": "ask_question",
        "question_id": question.id,
        "option_ids": option_ids,
    }
'''


def dump_json(obj: Any) -> str:
    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=True) + "\n"


def _instruction(kind: str) -> str:
    header = f"<!-- {GENERATED} -->\n\n"
    files = (
        "- `/app/case/patient_state.json` — synthetic patient (age, recorded protocol answers)\n"
        "- `/app/case/protocol.json` — Intelehealth Chest pain protocol (engineVersion 3.0)\n"
    )
    if kind == "one_shot_question":
        return (
            header
            + "Propose the next Chest pain history-taking question.\n\n"
            "This is CHW intake, not a doctor–patient consult. You choose the next "
            "protocol question or options. You do not interview a simulated patient.\n\n"
            "You are given:\n\n"
            + files
            + "\nWrite exactly one JSON object to `/app/proposal.json` with this shape:\n\n"
            "```json\n"
            "{\n"
            '  "schema_version": "0.1.0",\n'
            '  "protocol_id": "Chest pain",\n'
            '  "action": "ask_question",\n'
            '  "question_id": "ID_...",\n'
            '  "option_ids": ["ID_..."]\n'
            "}\n"
            "```\n\n"
            "Rules:\n\n"
            "- `question_id` must be a question node from protocol.json that has not already been answered.\n"
            "- `option_ids` must be every age-eligible option of that question. Omit age-ineligible options.\n"
            "- Do not invent IDs. Do not close the encounter.\n"
        )
    if kind == "one_shot_next":
        return (
            header
            + "Propose the next legal Chest pain intake action.\n\n"
            "This is CHW intake, not a doctor–patient consult. History is already in "
            "patient_state.json. You do not interview a simulated patient.\n\n"
            "You are given:\n\n"
            + files
            + "\nWrite exactly one JSON object to `/app/proposal.json`. "
            "The action is either `ask_question` or `close_and_act`.\n\n"
            "Ask:\n\n"
            "```json\n"
            "{\n"
            '  "schema_version": "0.1.0",\n'
            '  "protocol_id": "Chest pain",\n'
            '  "action": "ask_question",\n'
            '  "question_id": "ID_...",\n'
            '  "option_ids": ["ID_..."]\n'
            "}\n"
            "```\n\n"
            "Close:\n\n"
            "```json\n"
            "{\n"
            '  "schema_version": "0.1.0",\n'
            '  "protocol_id": "Chest pain",\n'
            '  "action": "close_and_act",\n'
            '  "disposition": "local_management"\n'
            "}\n"
            "```\n\n"
            "Rules:\n\n"
            "- If a protocol question is still legal, ask it. `option_ids` must be every "
            "age-eligible option of that question.\n"
            "- If no legal questions remain, close. "
            '`disposition` must be one of `"local_management"`, `"refer"`, `"urgent"`.\n'
            "- Do not invent IDs. Do not modify `patient_state.json`.\n"
            "- A hidden verifier grades the proposal against the protocol grammar and "
            "a separate demo policy that is not in this sandbox.\n"
        )
    if kind == "one_shot_close":
        return (
            header
            + "Close this Chest pain encounter and choose a disposition.\n\n"
            "This is CHW intake, not a doctor–patient consult. History is already in "
            "patient_state.json. You do not interview a simulated patient.\n\n"
            "You are given:\n\n"
            + files
            + "\nWrite exactly one JSON object to `/app/proposal.json` with:\n\n"
            "- `schema_version`: `\"0.1.0\"`\n"
            "- `protocol_id`: `\"Chest pain\"`\n"
            "- `action`: `\"close_and_act\"`\n"
            "- `disposition`: one of `\"local_management\"`, `\"refer\"`, `\"urgent\"`\n\n"
            "Do not invent patient facts. Do not modify `patient_state.json`. "
            "A hidden verifier grades the proposal against the protocol grammar and "
            "a separate demo policy that is not in this sandbox.\n"
        )
    return (
        header
        + "Conduct a full Chest pain history, then close.\n\n"
        "This is CHW intake, not a doctor–patient consult. You do not interview a "
        "simulated patient in free text.\n\n"
        "You are given:\n\n"
        + files
        + "- `/app/agent.py` — a working `propose()` that asks legal questions in protocol order\n\n"
        "Edit **only** the `CLOSE_DISPOSITION` assignment in `/app/agent.py`. "
        "Do not rewrite `propose()`. Do not change how questions or option lists are chosen.\n\n"
        '`CLOSE_DISPOSITION` must be one of `"local_management"`, `"refer"`, `"urgent"`.\n\n'
        "A hidden verifier steps `propose()`, fills answers from a chart you cannot see, "
        "and grades the close against a demo policy that is not in this sandbox.\n"
    )


def _task_toml(case: dict[str, Any]) -> str:
    artifact = "/app/agent.py" if case["task_kind"] == "rollout_intake" else "/app/proposal.json"
    return (
        f"# {GENERATED}\n"
        "schema_version = \"1.4\"\n"
        f"artifacts = [\"{artifact}\"]\n"
        "\n"
        "[task]\n"
        f"name = \"intelehealth-verify-v3/{case['case_id']}\"\n"
        "version = \"0.3.0\"\n"
        "description = \"Propose a Chest pain intake action for this case.\"\n"
        "keywords = [\"intelehealth\", \"protocol\", \"verification\"]\n"
        "\n"
        "[metadata]\n"
        "category = \"protocol-verification\"\n"
        "difficulty_explanation = \"Follow the protocol question tree and the action schema.\"\n"
        "protocol_file = \"Chest pain.json\"\n"
        "\n"
        "[verifier]\n"
        "timeout_sec = 120.0\n"
        "environment_mode = \"separate\"\n"
        "\n"
        "[verifier.environment]\n"
        "# Intended: no-network. Harbor's Docker provider only enforces that when the\n"
        "# daemon kernel has CONFIG_NFT_FIB_INET (nftables FIB). Docker Desktop's Linux\n"
        "# VM here does not, so Harbor rejects no-network. Isolation is the separate\n"
        "# verifier image, not egress policy.\n"
        "network_mode = \"public\"\n"
        "os = \"linux\"\n"
        "\n"
        "[agent]\n"
        "timeout_sec = 180.0\n"
        "\n"
        "[environment]\n"
        "os = \"linux\"\n"
        "network_mode = \"public\"\n"
        "build_timeout_sec = 600.0\n"
        "cpus = 1\n"
        "memory_mb = 2048\n"
    )


def _env_dockerfile(kind: str) -> str:
    extra = ""
    if kind == "rollout_intake":
        extra = "COPY agent.py /app/agent.py\n"
    return (
        f"# {GENERATED}\n"
        "FROM python:3.12-slim-bookworm\n"
        "WORKDIR /app\n"
        "RUN mkdir -p /app/case /logs/agent /logs/verifier\n"
        "COPY case/patient_state.json /app/case/patient_state.json\n"
        "COPY case/protocol.json /app/case/protocol.json\n"
        f"{extra}"
    )


def _tests_dockerfile(kind: str) -> str:
    extra = ""
    if kind == "rollout_intake":
        extra = "COPY case/patient_script.json /tests/case/patient_script.json\n"
    return (
        f"# {GENERATED}\n"
        "FROM python:3.12-slim-bookworm\n"
        "WORKDIR /app\n"
        "RUN mkdir -p /app /tests/case /logs/verifier \\\n"
        "    && pip install --no-cache-dir pytest\n"
        "COPY case/patient_state.json /tests/case/patient_state.json\n"
        "COPY case/protocol.json /tests/case/protocol.json\n"
        f"{extra}"
        "COPY protocol_walker.py grade.py encounter.py proposal_schema.json demo_rules.json test.sh test_proposal.py /tests/\n"
        "RUN chmod +x /tests/test.sh\n"
    )


def _test_sh() -> str:
    return (
        "#!/bin/bash\n"
        f"# {GENERATED}\n"
        "set -u\n"
        "mkdir -p /logs/verifier\n"
        "python3 /tests/grade.py\n"
        "grade_status=$?\n"
        "python3 -m pytest /tests/test_proposal.py -q --tb=short\n"
        "pytest_status=$?\n"
        "if [ \"$grade_status\" -ne 0 ] || [ \"$pytest_status\" -ne 0 ]; then\n"
        "  exit 1\n"
        "fi\n"
        "exit 0\n"
    )


def _test_proposal_py(kind: str) -> str:
    if kind == "rollout_intake":
        extra = """
    last = payload["steps"][-1]
    assert last["kind"] == "proposal"
    assert last["source"] == "agent"
    assert last["action"] == "close_and_act"
    assert len(payload["steps"]) >= 10
    answered = [s for s in payload["steps"] if s["kind"] == "answered"]
    assert answered
    assert all(s["source"] == "environment" for s in answered)
"""
    elif kind == "one_shot_close":
        extra = """
    last = payload["steps"][-1]
    assert last["kind"] == "proposal"
    assert last["source"] == "agent"
    assert last["action"] == "close_and_act"
"""
    elif kind == "one_shot_next":
        extra = """
    last = payload["steps"][-1]
    assert last["kind"] == "proposal"
    assert last["source"] == "agent"
    assert last["action"] in {"ask_question", "close_and_act"}
"""
    else:
        extra = """
    last = payload["steps"][-1]
    assert last["kind"] == "proposal"
    assert last["source"] == "agent"
    assert last["action"] == "ask_question"
"""
    return f'''"""Harbor pytest wrapper: grade.py already wrote reward.json. {GENERATED}"""

from __future__ import annotations

import json
from pathlib import Path

REWARD = Path("/logs/verifier/reward.json")
RECORD = Path("/logs/verifier/verification_record.json")
ENCOUNTER = Path("/logs/verifier/encounter.json")


def test_reward_file_exists():
    assert REWARD.exists(), "grade.py must write /logs/verifier/reward.json"


def test_verification_record_exists():
    assert RECORD.exists(), "grade.py must write /logs/verifier/verification_record.json"


def test_encounter_is_intake_trace():
    assert ENCOUNTER.exists(), "grade.py must write /logs/verifier/encounter.json"
    payload = json.loads(ENCOUNTER.read_text(encoding="utf-8"))
    assert payload["kind"] == "intake_encounter"
    assert payload["steps"]
{extra}

def test_reward_metrics_are_numeric():
    payload = json.loads(REWARD.read_text(encoding="utf-8"))
    for key in (
        "reward",
        "schema_valid",
        "legal_id",
        "age_ok",
        "nesting_ok",
        "completeness_ok",
        "safety_ok",
        "disposition_ok",
        "duplicate_free",
        "options_complete",
    ):
        assert key in payload
        assert isinstance(payload[key], (int, float))


def test_oracle_or_passing_agent_scores_one():
    payload = json.loads(REWARD.read_text(encoding="utf-8"))
    assert payload["reward"] == 1.0
    assert payload["legal_id"] == 1.0
    assert payload["duplicate_free"] == 1.0
    assert payload["options_complete"] == 1.0
'''


def _solve_oneshot(oracle: dict[str, Any]) -> str:
    body = json.dumps(oracle, indent=2, sort_keys=True)
    return (
        "#!/bin/bash\n"
        f"# {GENERATED}\n"
        "set -euo pipefail\n"
        "cat > /app/proposal.json << 'EOF'\n"
        f"{body}\n"
        "EOF\n"
    )


def _policy_agent(disposition: str) -> str:
    return f'''"""Oracle greedy intake agent. {GENERATED}

Asks the first legal unanswered question. Closes with a hardcoded disposition
for this fixture. This file is solution-only; it must not enter the agent image
as the scored answer. The environment stub leaves CLOSE_DISPOSITION empty.
"""

from __future__ import annotations

from typing import Any

CLOSE_DISPOSITION = "{disposition}"


def propose(state: dict[str, Any], protocol: Any) -> dict[str, Any]:
    age = int(state["age"])
    answers = state.get("answers") or []
    answered = {{a["question_id"] for a in answers if a.get("question_id")}}
    selected: set[str] = set()
    for answer in answers:
        selected.update(answer.get("option_ids") or [])
    legal = protocol.get_legal_next_questions(selected, answered, age)
    if not legal:
        return {{
            "schema_version": "0.1.0",
            "protocol_id": protocol.name,
            "action": "close_and_act",
            "disposition": CLOSE_DISPOSITION,
        }}
    question = legal[0]
    option_ids = [
        o.id
        for o in protocol.options_for(question.id)
        if protocol.is_age_eligible(o, age)
    ]
    return {{
        "schema_version": "0.1.0",
        "protocol_id": protocol.name,
        "action": "ask_question",
        "question_id": question.id,
        "option_ids": option_ids,
    }}
'''


def _solve_rollout() -> str:
    return (
        "#!/bin/bash\n"
        f"# {GENERATED}\n"
        "set -euo pipefail\n"
        'DIR="$(cd "$(dirname "$0")" && pwd)"\n'
        'cp "$DIR/agent.py" /app/agent.py\n'
    )


def _dataset_readme() -> str:
    return (
        f"# intelehealth-verify-v3\n\n"
        f"{GENERATED}\n\n"
        "Harbor tasks for Chest pain intake verification. Agent images contain protocol.json, "
        "patient_state.json, instruction.md, the environment Dockerfile, and (rollouts only) "
        "a stub `/app/agent.py` with empty `CLOSE_DISPOSITION`.\n\n"
        "Disposition labels are scored with a verifier-only synthetic DEMO_POLICY "
        "(`validated_clinically: false`). Chest pain.json does not define dispositions.\n\n"
        "Report grammar slices (age pair, nested ask vs illegal nested) separately from "
        "disposition slices (close labels, stub rollouts). Do not rank models on a blended mean.\n\n"
        "Passing these tasks does not demonstrate internal clinical understanding.\n\n"
        "Regenerate with `python shared/build_v3_tasks.py`.\n"
    )


def render() -> dict[str, bytes]:
    protocol = load_protocol(PROTOCOL_SRC)
    protocol_bytes = PROTOCOL_SRC.read_bytes()
    grader = {name: (SHARED / name).read_bytes() for name in GRADER_FILES}
    files: dict[str, bytes] = {}
    files["README.md"] = _dataset_readme().encode("utf-8")
    files["manifest.json"] = dump_json(manifest_payload()).encode("utf-8")
    files["GENERATED.txt"] = (GENERATED + "\n").encode("utf-8")

    for case in iter_cases():
        validate_case(case, protocol)
        prefix = case["case_id"]
        kind = case["task_kind"]
        files[f"{prefix}/instruction.md"] = _instruction(kind).encode("utf-8")
        files[f"{prefix}/task.toml"] = _task_toml(case).encode("utf-8")
        files[f"{prefix}/environment/Dockerfile"] = _env_dockerfile(kind).encode("utf-8")
        files[f"{prefix}/environment/case/patient_state.json"] = dump_json(
            case["patient_state"]
        ).encode("utf-8")
        files[f"{prefix}/environment/case/protocol.json"] = protocol_bytes
        files[f"{prefix}/tests/Dockerfile"] = _tests_dockerfile(kind).encode("utf-8")
        files[f"{prefix}/tests/test.sh"] = _test_sh().encode("utf-8")
        files[f"{prefix}/tests/test_proposal.py"] = _test_proposal_py(kind).encode("utf-8")
        files[f"{prefix}/tests/demo_rules.json"] = dump_json(DEMO_RULES).encode("utf-8")
        files[f"{prefix}/tests/case/patient_state.json"] = dump_json(
            case["patient_state"]
        ).encode("utf-8")
        files[f"{prefix}/tests/case/protocol.json"] = protocol_bytes
        files[f"{prefix}/tests/case/meta.json"] = dump_json(
            {
                "case_id": case["case_id"],
                "task_kind": case["task_kind"],
                "suite": case["suite"],
                "pair_id": case["pair_id"],
                "variant": case["variant"],
                "policy_id": case["policy_id"],
                "report_slice": case["report_slice"],
            }
        ).encode("utf-8")
        if case["oracle"] is not None:
            files[f"{prefix}/tests/case/oracle.json"] = dump_json(case["oracle"]).encode("utf-8")
        if case["patient_script"] is not None:
            files[f"{prefix}/tests/case/patient_script.json"] = dump_json(
                case["patient_script"]
            ).encode("utf-8")
        for name, payload in grader.items():
            files[f"{prefix}/tests/{name}"] = payload
        files[f"{prefix}/solution/solve.sh"] = (
            _solve_rollout() if kind == "rollout_intake" else _solve_oneshot(case["oracle"])
        ).encode("utf-8")
        if kind == "rollout_intake":
            files[f"{prefix}/environment/agent.py"] = STUB_AGENT.encode("utf-8")
            files[f"{prefix}/solution/agent.py"] = _policy_agent(
                case["close_disposition"]
            ).encode("utf-8")
    return files


def write_files(files: dict[str, bytes], dest: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    for rel, payload in files.items():
        path = dest / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
    for rel in existing_files(dest):
        if rel not in files:
            (dest / rel).unlink()


def existing_files(dest: Path) -> dict[str, bytes]:
    if not dest.is_dir():
        return {}
    out: dict[str, bytes] = {}
    for path in dest.rglob("*"):
        if path.is_file():
            rel = path.relative_to(dest).as_posix()
            out[rel] = path.read_bytes()
    return out


def diff_files(expected: dict[str, bytes], actual: dict[str, bytes]) -> list[str]:
    msgs: list[str] = []
    for rel in sorted(set(expected) | set(actual)):
        if rel not in actual:
            msgs.append(f"missing {rel}")
        elif rel not in expected:
            msgs.append(f"extra {rel}")
        elif expected[rel] != actual[rel]:
            msgs.append(f"mismatch {rel}")
    return msgs


def build() -> None:
    files = render()
    write_files(files, V3_ROOT)
    (SHARED / "v3_manifest.json").write_bytes(files["manifest.json"])


def check() -> int:
    expected = render()
    actual = existing_files(V3_ROOT)
    msgs = diff_files(expected, actual)
    shared_manifest = SHARED / "v3_manifest.json"
    if not shared_manifest.is_file() or shared_manifest.read_bytes() != expected["manifest.json"]:
        msgs.append("mismatch shared/v3_manifest.json")
    if msgs:
        print("V3 task tree is stale or dirty:")
        for msg in msgs:
            print(f"  {msg}")
        return 1
    print(f"V3 tasks match generator ({len(expected)} files)")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="compare disk to generator; do not write")
    args = parser.parse_args(argv)
    if args.check:
        return check()
    build()
    print(f"wrote {V3_ROOT}")
    return check()


if __name__ == "__main__":
    raise SystemExit(main())
